---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: visualizer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: visualizer
  template:
    metadata:
      labels:
        app: visualizer
    spec:
      containers:
      - name: visualizer
        image: dockersamples/visualizer:latest
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: visualizer
spec:
  type: LoadBalancer
  selector:
    app: visualizer
  ports:
    - port: 80
      targetPort: 8080
